### ISSUE TITLE
qstat cache

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/gogridengine#7]
## constraints

* should be concurrency safe

## notes

* should check the dynamic of the sge cache, no point in us polling it more often than it itself would update the status of the workers.

## Fronted Caching
* As an option, we could actually deploy Varnish in front of services using the library. 
  * This means that little to no changes would have to happen to the core library or other services
  * Also means that every individual query caches it's respective result set. 
  * Risk wise seems high though. It's another piece of machinery to manage that we'd have to figure out how to deploy and configure correctly. 

## Localized Caching
* Caching makes more sense locally, and something like gopher, ristretto, etc would make sense. 
* Even before we determine which one, we need to figure out *how* to cache the data. 
  * Caching the entire list of jobs
     * Would be the simplest approach
     * Would allow for a unified filtering / paging target
     * Would generate a lot of memory churn as we dump and repopulate
  * Caching individual jobs
     * More effective of memory and the cache as hotter items remain cached longer
     * Means we would have to find a way to poll all of the cache and look for deltas in order to manage removing items from the cache
     * Feels like it's way more work than it would buy us
     * Seems higher risk purely because of us having to invent a way to manage the data this way.

**Comment by dpastoor** [comment]
Per #8 as we consider a cache first lets confirm we really need a cache, and if so how soon. 

What is the parsing time required for the following number of jobs:

* 10
* 100 
* 1000
* 10000
* 50000

**Comment by shairozan** [comment]
So I can fake scenarios with the numbers provided by changing up how the test data is generated. We may process an environment variable for JobsToGenerate, and iterate over it, evenly distributing them between running / pending. This will technically be *more* expensive than the actual operation since we have to create the object, serialize to XML, then deserialize for the rest of the application, but it'll be a good point of reference. 

Then I can use [hey](https://github.com/rakyll/hey) or some other load tester to hit chokmah with large batteries of requests to see what the percentile distribution of time to first response is. 

In regards to #6 , providing a cache and having the filter done by qstat poses a scenario where the cache does you little good. Unless you're storing a new set of cache data for every filter combination as they come up, you get into a scenario where filtered queries have to invalidate the cache and repopulate it. You'd basically be turning the cache into a "as the query changes" kind of solution, at which point we wouldn't be far off from just not needing the cache altogether. 

What makes more sense to me is to cache all of the jobs, and then apply filters / pagination against that data arbitrarily in go. It provides us a uniform point from which to access and manipulate the data, and we can be certain that, shy of jobs completing and falling off the stack there are no situations based on queries that we would need to go back to qstat until our TTL has expired on the cache.

**Comment by shairozan** [comment]
If you wanted to filter at the qstat level, it might make more sense to implement something like varnish in front of chokhmah to cache entire response sets. In that scenario, requests that are matched and already in the cache never even make it to Chokhmah

**Comment by shairozan** [comment]
When it comes to caching, if we go with ristretto for example, we'll need to make sure we understand the eviction policies well enough up front to establish our policies around transaction costs etc.

**Comment by shairozan** [comment]
From my tests so far, it looks like that with 100K jobs, the memory footprint of the cache would be 43-45 MB
